In [1]:
import pandas as pd
df=pd.read_csv('movies_metadata.csv')
df.head()

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_2864\181086072.py:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('movies_metadata.csv')

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [2]:
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,45456,45457,45458,45459,45460,45461,45462,45463,45464,45465
adult,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
belongs_to_collection,"{'id': 10194, 'name': 'Toy Story Collection', ...",NaN,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",NaN,"{'id': 96871, 'name': 'Father of the Bride Col...",NaN,NaN,NaN,NaN,"{'id': 645, 'name': 'James Bond Collection', '...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
budget,30000000,65000000,0,16000000,0,60000000,58000000,0,35000000,58000000,...,0,0,0,0,0,0,0,0,0,0
genres,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...","[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","[{'id': 35, 'name': 'Comedy'}]","[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...","[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...","[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",...,"[{'id': 27, 'name': 'Horror'}, {'id': 9648, 'n...","[{'id': 9648, 'name': 'Mystery'}, {'id': 27, '...","[{'id': 27, 'name': 'Horror'}]","[{'id': 878, 'name': 'Science Fiction'}]","[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...","[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...","[{'id': 18, 'name': 'Drama'}]","[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",[],[]
homepage,http://toystory.disney.com/toy-story,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.mgm.com/view/movie/757/Goldeneye/,...,NaN,NaN,NaN,NaN,NaN,http://www.imdb.com/title/tt6209470/,NaN,NaN,NaN,NaN
id,862,8844,15602,31357,11862,949,11860,45325,9091,710,...,84419,390959,289923,222848,30840,439050,111109,67758,227506,461257
imdb_id,tt0114709,tt0113497,tt0113228,tt0114885,tt0113041,tt0113277,tt0114319,tt0112302,tt0114576,tt0113189,...,tt0038621,tt0265736,tt0252966,tt0112613,tt0102797,tt6209470,tt2028550,tt0303758,tt0008536,tt6980792
original_language,en,en,en,en,en,en,en,en,en,en,...,en,en,en,en,en,fa,tl,en,en,en
original_title,Toy Story,Jumanji,Grumpier Old Men,Waiting to Exhale,Father of the Bride Part II,Heat,Sabrina,Tom and Huck,Sudden Death,GoldenEye,...,House of Horrors,Shadow of the Blair Witch,The Burkittsville 7,Caged Heat 3000,Robin Hood,رگ خواب,Siglo ng Pagluluwal,Betrayal,Satana likuyushchiy,Queerama
overview,"Led by Woody, Andy's toys live happily in his ...",When siblings Judy and Peter discover an encha...,A family wedding reignites the ancient feud be...,"Cheated on, mistreated and stepped on, the wom...",Just when George Banks has recovered from his ...,"Obsessive master thief, Neil McCauley leads a ...",An ugly duckling having undergone a remarkable...,"A mischievous young boy, Tom Sawyer, witnesses...",International action superstar Jean Claude Van...,James Bond must unmask the mysterious head of ...,...,An unsuccessful sculptor saves a madman named ...,"In this true-crime documentary, we delve into ...",A film archivist revisits the story of Rustin ...,It's the year 3000 AD. The world's most danger...,"Yet another version of the classic epic, with ...",Rising and falling between a man and woman.,An artist struggles to finish his work while a...,"When one of her hits goes wrong, a professiona...","In a small town live two brothers, one a minis...",50 years after decriminalisation of homosexual...
popularity,21.946943,17.015539,11.7129,3.859495,8.387519,17.924927,6.677277,2.561161,5.23158,14.686036,...,0.222814,0.076061,0.38645,0.661558,5.683753,0.072051,0.178241,0.903007,0.003503,0.163015
poster_path,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,/e64sOI48hQXyru7naBFyssKFxVd.jpg,/zMyfPUelumio3tiDKPffaUpsQTD.jpg,/jQh15y5YB7bWz1NtffNZmRw0s9D.jpg,/sGO5Qa55p7wTu7FJcX4H4xIVKvS.jpg,/eoWvKD60lT95Ss1MYNgVExpo5iU.jpg,/5c0ovjT41KnYIHYuF4AWsTe3sKh.jpg,...,/yMnq9mL5uYxbRgwKqyz1cVGCJYJ.jpg,/q75tCM4pFmUzdCg0gqcOQquCaYf.jpg,/lXtoHVdej6kS1Dc7KAhw05sMos9.jpg,/4lF9LH0b0Z1X94xGK9IOzqEW6k1.jpg,/fQC46NglNiEMZBv5XHoyLuOWoN5.jpg,/jldsYflnId4tTWPx8es3uzsB1I8.jpg,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg,/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg,/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg
production_companies,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'name': 'Warner Bros.', 'id': 6194}, {'name'...",[{'name': 'Twentieth Century Fox Film Corporat...,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'name': 'Regency Enterprises', 'id': 508}, {...","[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'name': 'Walt Disney Pictures', 'id': 2}]","[{'name': 'Universal Pictures', 'id': 33}, {'n...","[{'name': 'United Artists', 'id': 60}, {'name'...",...,"[{'name': 'Universal Pictures', 'id': 33}]",[],"[{'name': 'Neptune Salad Entertainment', 'id':...","[{'name': 'Concorde-New Horizons', 'id': 4688}]","[{'name': 'Westdeutscher Rundfunk (WDR)', 'id'...",[],"[{'name': 'Sine Olivia', 'id': 19653}]","[{'name': 'American World Pictures', 'id': 6165}]","[{'name': 'Yermoliev', 'id': 88753}]",[]
production_countries,"[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'DE', 'name': 'Germany'}, {'is...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",...,"[{'iso_3166_1': 'US', 'name': 'United States o...",[],"[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...","[{'iso_3166_1': 'IR', 'name': 'Iran'}]","[{'iso_3166_1': 'PH', 'name': 'Philippines'}]","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'RU', 'name': 'Russia'}]","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]"
release_date,1995-10-30,1995-12-15,1995-12-22,1995-12-22,1995-02-10,1995-12-15,1995-12-15,1995-12-22,1995-12-22,1995-11-16,...,1946-03-29,2000-10-22,2000-10-03,1995-01-01,1991-05-13,NaN,2011-11-17,2003-08-01,1917-10-21,2017-06-09
revenue,373554033.0,262797249.0,0.0,81452156.0,76578911.0,187436818.0,0.0,0.0,64350171.0,352194034.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
runtime,81.0,104.0,101.0,127.0,106.0,170.0,127.0,97.0,106.0,130.0,...,65.0,45.0,30.0,85.0,104.0,90.0,360.0,90.0,87.0,75.0
spoken_languages,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}, {'iso...","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}, {'iso...","[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...","[{'iso_639_1': 'en', 'name': 'English'}, {'iso...","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",...,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'fa', 'name': 'فارسی'}]","[{'iso_639_1': 'tl', 'name': ''}]","[{'iso_639_1': 'en', 'name': 'English'}]",[],"[{'iso_639_1': 'en', 'name': 'English'}]"
status,Released,Released,Released,Released,Released,Released,Released,Released,Released,Released,...,Released,Released,Released,Released,Released,Released,Released,Released,Released,Released
tagline,NaN,Roll the dice and unleash the excitement!,Still Yelling. Still Fighting. Still Ready for...,Friends are the people who let you be yourself...,Just When His World Is Back To Normal... He's ...,A Los Angeles Crime Saga,You are cordially invited to the most surprisi...,The Original Bad Boys.,Terror goes into overtime.,No limits. No fears. No substitutes.,...,Meet...The CREEPER!,NaN,"Do you know what happened 50 years before ""The...",NaN,NaN,Rising and falling between a man and woman,NaN,A deadly game of wits.,NaN,NaN
title,Toy Story,Jumanji,Grumpier Old Men,Waiting to Exhale,Father of the Bride Part II,Heat,Sabrina,Tom and Huck,Sudden Death,GoldenEye,...,House of Horrors,Shadow of the Blair Witch,The Burkittsville 7,Caged Heat 3000,Robin Hood,Subdue,Century of Birthing,Betrayal,Satan Triumphant,Queerama
video,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
vote_average,7.7,6.9,6.5,6.1,5.7,7.7,6.2,5.4,5.5,6.6,...,6.3,7.0,7.0,3.5,5.7,4.0,9.0,3.8,0.0,0.0
vote_count,5415.0,2413.0,92.0,34.0,173.0,1886.0,141.0,45.0,174.0,1194.0,...,8.0,2.0,1.0,1.0,26.0,1.0,3.0,6.0,0.0,0.0

In [3]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [5]:
df.describe()

            revenue       runtime  vote_average    vote_count
count  4.546000e+04  45203.000000  45460.000000  45460.000000
mean   1.120935e+07     94.128199      5.618207    109.897338
std    6.433225e+07     38.407810      1.924216    491.310374
min    0.000000e+00      0.000000      0.000000      0.000000
25%    0.000000e+00     85.000000      5.000000      3.000000
50%    0.000000e+00     95.000000      6.000000     10.000000
75%    0.000000e+00    107.000000      6.800000     34.000000
max    2.787965e+09   1256.000000     10.000000  14075.000000

# Understanding the dataset

In [6]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [7]:
df['imdb_id']

0        tt0114709
1        tt0113497
2        tt0113228
3        tt0114885
4        tt0113041
           ...
45461    tt6209470
45462    tt2028550
45463    tt0303758
45464    tt0008536
45465    tt6980792
Name: imdb_id, Length: 45466, dtype: object

In [8]:
df=df.drop('imdb_id',axis=1)
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,45456,45457,45458,45459,45460,45461,45462,45463,45464,45465
adult,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
belongs_to_collection,"{'id': 10194, 'name': 'Toy Story Collection', ...",NaN,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",NaN,"{'id': 96871, 'name': 'Father of the Bride Col...",NaN,NaN,NaN,NaN,"{'id': 645, 'name': 'James Bond Collection', '...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
budget,30000000,65000000,0,16000000,0,60000000,58000000,0,35000000,58000000,...,0,0,0,0,0,0,0,0,0,0
genres,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...","[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","[{'id': 35, 'name': 'Comedy'}]","[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...","[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...","[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",...,"[{'id': 27, 'name': 'Horror'}, {'id': 9648, 'n...","[{'id': 9648, 'name': 'Mystery'}, {'id': 27, '...","[{'id': 27, 'name': 'Horror'}]","[{'id': 878, 'name': 'Science Fiction'}]","[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...","[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...","[{'id': 18, 'name': 'Drama'}]","[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",[],[]
homepage,http://toystory.disney.com/toy-story,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.mgm.com/view/movie/757/Goldeneye/,...,NaN,NaN,NaN,NaN,NaN,http://www.imdb.com/title/tt6209470/,NaN,NaN,NaN,NaN
id,862,8844,15602,31357,11862,949,11860,45325,9091,710,...,84419,390959,289923,222848,30840,439050,111109,67758,227506,461257
original_language,en,en,en,en,en,en,en,en,en,en,...,en,en,en,en,en,fa,tl,en,en,en
original_title,Toy Story,Jumanji,Grumpier Old Men,Waiting to Exhale,Father of the Bride Part II,Heat,Sabrina,Tom and Huck,Sudden Death,GoldenEye,...,House of Horrors,Shadow of the Blair Witch,The Burkittsville 7,Caged Heat 3000,Robin Hood,رگ خواب,Siglo ng Pagluluwal,Betrayal,Satana likuyushchiy,Queerama
overview,"Led by Woody, Andy's toys live happily in his ...",When siblings Judy and Peter discover an encha...,A family wedding reignites the ancient feud be...,"Cheated on, mistreated and stepped on, the wom...",Just when George Banks has recovered from his ...,"Obsessive master thief, Neil McCauley leads a ...",An ugly duckling having undergone a remarkable...,"A mischievous young boy, Tom Sawyer, witnesses...",International action superstar Jean Claude Van...,James Bond must unmask the mysterious head of ...,...,An unsuccessful sculptor saves a madman named ...,"In this true-crime documentary, we delve into ...",A film archivist revisits the story of Rustin ...,It's the year 3000 AD. The world's most danger...,"Yet another version of the classic epic, with ...",Rising and falling between a man and woman.,An artist struggles to finish his work while a...,"When one of her hits goes wrong, a professiona...","In a small town live two brothers, one a minis...",50 years after decriminalisation of homosexual...
popularity,21.946943,17.015539,11.7129,3.859495,8.387519,17.924927,6.677277,2.561161,5.23158,14.686036,...,0.222814,0.076061,0.38645,0.661558,5.683753,0.072051,0.178241,0.903007,0.003503,0.163015
poster_path,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,/e64sOI48hQXyru7naBFyssKFxVd.jpg,/zMyfPUelumio3tiDKPffaUpsQTD.jpg,/jQh15y5YB7bWz1NtffNZmRw0s9D.jpg,/sGO5Qa55p7wTu7FJcX4H4xIVKvS.jpg,/eoWvKD60lT95Ss1MYNgVExpo5iU.jpg,/5c0ovjT41KnYIHYuF4AWsTe3sKh.jpg,...,/yMnq9mL5uYxbRgwKqyz1cVGCJYJ.jpg,/q75tCM4pFmUzdCg0gqcOQquCaYf.jpg,/lXtoHVdej6kS1Dc7KAhw05sMos9.jpg,/4lF9LH0b0Z1X94xGK9IOzqEW6k1.jpg,/fQC46NglNiEMZBv5XHoyLuOWoN5.jpg,/jldsYflnId4tTWPx8es3uzsB1I8.jpg,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg,/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg,/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg
production_companies,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'name': 'Warner Bros.', 'id': 6194}, {'name'...",[{'name': 'Twentieth Century Fox Film Corporat...,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'name': 'Regency Enterprises', 'id': 508}, {...","[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'name': 'Walt Disney Pictures', 'id': 2}]","[{'name': 'Universal Pictures', 'id': 33}, {'n...","[{'name': 'United Artists', 'id': 60}, {'name'...",...,"[{'name': 'Universal Pictures', 'id': 33}]",[],"[{'name': 'Neptune Salad Entertainment', 'id':...","[{'name': 'Concorde-New Horizons', 'id': 4688}]","[{'name': 'Westdeutscher Rundfunk (WDR)', 'id'...",[],"[{'name': 'Sine Olivia', 'id': 19653}]","[{'name': 'American World Pictures', 'id': 6165}]","[{'name': 'Yermoliev', 'id': 88753}]",[]
production_countries,"[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'DE', 'name': 'Germany'}, {'is...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",...,"[{'iso_3166_1': 'US', 'name': 'United States o...",[],"[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...","[{'iso_3166_1': 'IR', 'name': 'Iran'}]","[{'iso_3166_1': 'PH', 'name': 'Philippines'}]","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'RU', 'name': 'Russia'}]","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]"
release_date,1995-10-30,1995-12-15,1995-12-22,1995-12-22,1995-02-10,1995-12-15,1995-12-15,1995-12-22,1995-12-22,1995-11-16,...,1946-03-29,2000-10-22,2000-10-03,1995-01-01,1991-05-13,NaN,2011-11-17,2003-08-01,1917-10-21,2017-06-09
revenue,373554033.0,262797249.0,0.0,81452156.0,76578911.0,187436818.0,0.0,0.0,64350171.0,352194034.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
runtime,81.0,104.0,101.0,127.0,106.0,170.0,127.0,97.0,106.0,130.0,...,65.0,45.0,30.0,85.0,104.0,90.0,360.0,90.0,87.0,75.0
spoken_languages,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}, {'iso...","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}, {'iso...","[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...","[{'iso_639_1': 'en', 'name': 'English'}, {'iso...","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",...,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'fa', 'name': 'فارسی'}]","[{'iso_639_1': 'tl', 'name': ''}]","[{'iso_639_1': 'en', 'name': 'English'}]",[],"[{'iso_639_1': 'en', 'name': 'English'}]"
status,Released,Released,Released,Released,Released,Released,Released,Released,Released,Released,...,Released,Released,Released,Released,Released,Released,Released,Released,Released,Released
tagline,NaN,Roll the dice and unleash the excitement!,Still Yelling. Still Fighting. Still Ready for...,Friends are the people who let you be yourself...,Just When His World Is Back To Normal... He's ...,A Los Angeles Crime Saga,You are cordially invited to the most surprisi...,The Original Bad Boys.,Terror goes into overtime.,No limits. No fears. No substitutes.,...,Meet...The CREEPER!,NaN,"Do you know what happened 50 years before ""The...",NaN,NaN,Rising and falling between a man and woman,NaN,A deadly game of wits.,NaN,NaN
title,Toy Story,Jumanji,Grumpier Old Men,Waiting to Exhale,Father of the Bride Part II,Heat,Sabrina,Tom and Huck,Sudden Death,GoldenEye,...,House of Horrors,Shadow of the Blair Witch,The Burkittsville 7,Caged Heat 3000,Robin Hood,Subdue,Century of Birthing,Betrayal,Satan Triumphant,Queerama
video,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
vote_average,7.7,6.9,6.5,6.1,5.7,7.7,6.2,5.4,5.5,6.6,...,6.3,7.0,7.0,3.5,5.7,4.0,9.0,3.8,0.0,0.0
vote_count,5415.0,2413.0,92.0,34.0,173.0,1886.0,141.0,45.0,174.0,1194.0,...,8.0,2.0,1.0,1.0,26.0,1.0,3.0,6.0,0.0,0.0

In [9]:
df[df['original_title'] !=df['title']] [['original_title','title']].head()

                      original_title                      title
28        La Cité des Enfants Perdus  The City of Lost Children
29                         摇啊摇，摇到外婆桥             Shanghai Triad
32  Guillaumet, les ailes du courage           Wings of Courage
57                        Il postino                The Postman
58                  Le confessionnal           The Confessional

In [10]:
df=df.drop('original_title',axis=1)

In [11]:
df['revenue'].head(30)

0     373554033.0
1     262797249.0
2             0.0
3      81452156.0
4      76578911.0
5     187436818.0
6             0.0
7             0.0
8      64350171.0
9     352194034.0
10    107879496.0
11            0.0
12     11348324.0
13     13681765.0
14     10017322.0
15    116112375.0
16    135000000.0
17      4300000.0
18    212385533.0
19     35431113.0
20    115101622.0
21            0.0
22     30303072.0
23            0.0
24     49800000.0
25            0.0
26     27400000.0
27            0.0
28      1738611.0
29            0.0
Name: revenue, dtype: float64

In [12]:
df[df['revenue']==0].shape

(38052, 22)

In [13]:
import numpy as np
df['revenue']=df['revenue'].replace(0,np.nan)
df[df['revenue'].isnull()].shape

(38058, 22)

In [14]:
df['budget'].head(20)

0     30000000
1     65000000
2            0
3     16000000
4            0
5     60000000
6     58000000
7            0
8     35000000
9     58000000
10    62000000
11           0
12           0
13    44000000
14    98000000
15    52000000
16    16500000
17     4000000
18    30000000
19    60000000
Name: budget, dtype: object

In [15]:
#idk,what is this
df['budget']=pd.to_numeric(df['budget'], errors='coerce')
df['budget']=df['budget'].replace(0,np.nan)

In [16]:
df[df['budget'].isnull()].shape

(36576, 22)

In [21]:
df['return']=(df['revenue']-df['budget']/df['budget'])**100

In [24]:
df[df['return'].isnull()].shape

(40085, 23)